-- Create tables
CREATE TABLE GYM (
    GymID INT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Address VARCHAR(100),
    Telephone VARCHAR(15)
);

CREATE TABLE MEMBER (
    MemberID INT PRIMARY KEY,
    LastName VARCHAR(50) NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    Address VARCHAR(100),
    DateOfBirth DATE,
    Gender CHAR(1),
    GymID INT,
    FOREIGN KEY (GymID) REFERENCES GYM(GymID)
);

-- Add new columns
ALTER TABLE PRODUCT
ADD Category VARCHAR2(20);

ALTER TABLE ORDERS
ADD OrderDate DATE DEFAULT SYSDATE;


ALTER TABLE PRODUCT
ADD Category VARCHAR2(20);

ALTER TABLE ORDERS
ADD OrderDate DATE DEFAULT SYSDATE;
